name: Snap Publish

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.ref }}
  cancel-in-progress: true

jobs:
  Snap:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for version determination

      - id: build-snap
        name: Build the snap
        uses: canonical/actions/build-snap@release
        with:
          snapcraft-channel: candidate
          review-opts: "--allow-classic"

      - name: Store the snap as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-snap.outputs.snap-name }}
          path: ${{ steps.build-snap.outputs.snap-path }}

      - name: Publish the snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build-snap.outputs.snap }}
          release: edge

